# --- build  ---
FROM golang:1.23 AS builder

WORKDIR /app

COPY sub/go.mod sub/go.sum ./
RUN --mount=type=cache,target=/go/pkg/mod go mod download

COPY sub/ .
#RUN CGO_ENABLED=0 GOOS=linux go build -o subscriber main.go
RUN --mount=type=cache,target=/root/.cache/go-build CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o subscriber main.go

# ---- Runtime ----
#FROM gcr.io/distroless/base
FROM debian:bookworm-slim
COPY --from=builder /app/subscriber /subscriber

ENTRYPOINT ["/subscriber"]

