# ---- Build ----
FROM golang:1.23 AS builder

WORKDIR /app

COPY pub/go.mod pub/go.sum ./

#RUN go mod tidy
RUN --mount=type=cache,target=/go/pkg/mod go mod download
COPY pub/ .
#RUN CGO_ENABLED=0 GOOS=linux go build -o publisher main.go
RUN --mount=type=cache,target=/root/.cache/go-build CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o publisher ./main.go

# ---- Runtime ----
FROM debian:bookworm-slim

RUN apt-get update && apt-get install -y --no-install-recommends nmap ca-certificates && rm -rf /var/lib/apt/lists/*

COPY --from=builder /app/publisher /publisher

ENTRYPOINT ["/publisher"]

